# Generated by Django 6.1.1 on 2026-09-12 02:43

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcontacto',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='solicitudcontacto',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudcontacto',
            name='plan_interes',
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='planes_solicitados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='total_estimado_clp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='categoriaplan',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='categoriaplan',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoriaplan',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_clp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
